[package]
name = "ratings"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", features = ["json"] }
dotenv = "0.15.0"
futures = "0.3.28"
http = "0.2.9"
hyper = { version = "0.14.26", features = ["full"] }
mongodb = "2.5.0"
prost = "0.11.9"
reqwest = "0.11.18"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tonic = "0.9.2"
tonic-reflection = "0.9.2"
tower = "0.4.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[build-dependencies]
tonic-build = { version = "0.9", features = ["prost"] }
