[package]
name = "urate"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", features = ["json"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
hyper = { version = "0.14.26", features = ["full"] }
log = "0.4.19"
mongodb = "2.5.0"
reqwest = "0.11.18"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tower = "0.4.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
