name: Build and test

on:
  workflow_call:

jobs:
  build:
    name: Build Ratings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config protobuf-compiler

      - name: Check code formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -Dwarnings

      - name: Setup and Run Tests
        run: |
          cargo install cargo-make
          cargo install dotenvy --features=cli
          cargo make full-test
