name: Lints

on:
  workflow_call:

jobs:
  build:
    name: Lint for style issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check commit style
        uses: webiny/action-conventional-commits@v1.3.0
