name: Pull Request

on:
  pull_request:
    paths-ignore:
      - vm_operator/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  cla:
    uses: ./.github/workflows/cla.yaml
