name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - operator/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ./.github/workflows/build-charm.yaml